---
- hosts: [webserver]
  become: yes
  tasks:
  - name: install webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="debian"
  - name: start webserver
    service:
     name: apache2
     state: started
    when: ansible_os_family =="debian"

